### ISSUE TITLE
Project 2: public api

### ISSUE THREAD

**Issue by sockeqwe** [PokemonGoers/HashPokemonGo#3]
Provide a public api (via websockets) to listen for mob detection event in a certain area.

Research if it is possible to pass url parameters for lat / lng

**Comment by sacdallago** [comment]
Again, just to keep it simple: you might want to implement this directly in project A!
But not necessarily! :) This part you can also develop on your own, since it's not gonna deal with the database directly, or with anything coded in A
Also, at the end of the day just the API is not gonna be enough, you want to integrate this with the @PokemonGoers/pokemap-1 @PokemonGoers/pokemap-2 projects to display the live-feed on a map
