### ISSUE TITLE
Project 3: public API

### ISSUE THREAD

**Issue by sockeqwe** [PokemonGoers/HashPokemonGo#8]
Caller is interested in a certain pokemon 

Dataformat has to be specified (maybe json, maybe svg ...)

**Comment by sacdallago** [comment]
You don't need to implement this ;)

That's what @PokemonGoers/pokedata is for!

**Comment by sockeqwe** [comment]
Thanks @sacdallago  for your feedback. Just to clarify that:
We don't have to provide any REST endpoint or WebSocket a client can connect to us? Is it the responsibility of @PokemonGoers/pokedata  to provide the public API for all clients?
So we basically build a library and provide a traditional callback based system to connect to our data?

**Comment by phdowling** [comment]
For context: this would be an API call that provides sentiment analysis of historic tweets for a certain pokemon (either as JSON or maybe even as a ready-made sentiment trend graph)- I'm not sure if this is quite part of the pokedata project scope. Could we get some more input @sacdallago ?

**Comment by sacdallago** [comment]
So. It is tricky.

It is not part of the pokedata project to implement the analysis, though there shouldn't be scattered APIs around, but one central API.
You can either build a package that you then publish to npm and that project A uses on the tweets (the traditional twitter rest api) to perform the sentiment analysis. But then would still need to store this data within the same database and expose a service to access it. That's why I said you should collaborate with them: they can assist you with understanding how to build services on top of their code, but you should build the scoring, retrieval and storing yourselves.

And this year they are already using the twitter API for a different purpose, so you might as well start from there (notice: they have that already implemented).

For the live-analysis it's different. You don't need to store anything back in the database. Ideally you just spawn a listener for that user at that moment in time (with that lat-lng) and you get the live tweets with sentiment scoring and mobs (the latter being more important).

This, to me, sounds a lot like something you can package into an npm package which can be used by the @PokemonGoers/pokemap-1 @PokemonGoers/pokemap-2 folks to display the data on the map
